apiVersion: v1
kind: Secret
metadata:
  name:  postgres-credentials
  namespace: {{ .Values.namespace }}
data:
  # echo -n 'postgres' | base64
  # echo -n 'cG9zdGdyZXM=' | base64 -d
  user: {{ .Values.secrets.postgresUser }}
  # echo -n 'mysecretpassword' | base64
  # echo -n 'bXlzZWNyZXRwYXNzd29yZA==' | base64 -d
  password: {{ .Values.secrets.postgresPassword }}