apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.serviceName }}
  namespace:   {{ .Values.namespace }}
  labels:
    app: database
spec:
  ports:
    - port: {{ .Values.postgres.containerPort }}
  selector:
    app: database