apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.backend.serviceName }}
spec:
  ports:
    - port: {{ .Values.backend.containerPort }}
      targetPort: {{ .Values.backend.containerPort }}
  selector:
    app: flask-app